### PR TITLE
initializes firebase and sends beer to db

### PR DESCRIPTION
**Pull request by catslug**

### CODE REVIEW

**Comment by catslug** [comment]
Bloop. I swear I checked to see if this was here before I pushed, and yet now I'm seeing that the conflict is that I'm pushing the same info into this twice?

**Comment by sarahjelt** [comment]
Oh hmm... are you able to resolve the conflicts/merge this one?

**Comment by sarahjelt** [comment]
Oh wait or can this be closed? I only ask because I was going to push some DOM changes in!

**Comment by catslug** [comment]
I have no idea what I was looking at last night, but this does need to merge in. Let me see if I can resolve the conflicts. They're minor.

**Comment by catslug** [comment]
Okay, it's resolved with no more conflicts! I"ll wait for a thumb's up before completing the merge.

**Pull request merged**
